### ISSUE TITLE
Investigate getting mtime from server rather than files.xml in download.

### ISSUE THREAD

**Issue by jjjake** [jjjake/internetarchive#139]
There are cases where files.xml does not have the mtime available (usually when a task has redrowed, and the files.xml did not update). I'm considering getting the mtime from the server via a HEAD request, but there are some considerations to keep in mind:
- This isn't very common (I think), and it only is an issue when the item itself is "broken".
- The mtime from the server is slightly different than what is in files.xml. Any downloads done with an older client will have slightly different mtimes, and sync won't work.
- The overhead of an extra request for every file.

**Comment by bfalling** [comment]
One other consideration is that using file mtime eliminates a hidden dependency, especially since I think most people think of "download" functionality as pulling files straight down from a source, without manipulating them or modifying them in any way, let alone modifying them based on some other file somewhere.

**Comment by samuel-archive** [comment]
i believe the http last-modified header should be a reliable time to use
