### ISSUE TITLE
upload --spreadsheet defaults collection to non-test_collection

### ISSUE THREAD

**Issue by ewenmcneill** [jjjake/internetarchive#148]
It appears that if you do `ia upload --spreadsheet=foo.csv` and your spreadsheet doesn't specify a `collection` column, then `ia` will (a) continue with the upload, (b) pick an arbitrary collection and (c) that arbitrary collection is _not_ `test_collection`.  Which means that there's a non-trivial risk of uploading a mass of things to a non-test collection, realising too late that they're in the wrong collection, and then... you're stuck. (AFAICT only archive.org admins can move things between collections, or delete items.)

I think it would be better to either:
(a) refuse to upload from a CSV that doesn't specify `collection`; or
(b) default the collection to `test_collection`, where at least the mistakes will get auto-removed after a few weeks.

Ewen

PS: In my case the collection seemed to default to `opensource`, but I'm not clear how; it was a `mediatype=software` upload, which had `topic[N]=opensource`, so possibly that was the trigger.  But it's still not the right collection as [`opensource`](https://archive.org/details/opensource) on archive.org is used for another "open source" meaning (not software).

**Comment by jjjake** [comment]
Good point @ewen-naos-nz, 'preciate raising the issue. Thank you.

I think I prefer refusing the upload if a collection isn't specified. I don't like the idea of defaulting to `test_collection`, as it might no be clear that the users uploads will be removed after ~30 days if they're not paying attention.

Perhaps `mediatype` should be required as well. Right now it defaults to `data`, which is probably inaccurate for most uploads, and I'm sure many users don't think to set `mediatype`. Another option would be to try and guess the mediatype based on the file extension or mime-type, but this would likely require adding `python-magic` or something similar to the requirements. I want to be careful about adding dependencies. If we did this, maybe it'd even make sense to not require a collection be specified, and we could try and guess a collection based on mediatype (if one isn't specified).

Let me think about this for a bit, and let's give a chance for others to give feedback on this issue.

**Comment by wumpus** [comment]
Postel's Law is dead :-) seriously, I'm all for making collection and mediatype be intentional decisions by the uploader. The error messages need to point users at the docs.

**Comment by ewen-naos-nz** [comment]
I think it'd be reasonable to require `mediatype` to be explicitly specified too, at least in "spreadsheet" mode, as it's another metadata item which cannot be changed later.  (My first test upload didn't have mediatype, and ended up being "data" -- fortunately that one went into `test_collection`; the "missing collection" problem came about when I wrote a tool to generate the spreadsheet from a directory listing and overlooked exporting the `collection` field.... :-) )

The only caveat I'd make is that it appears that there's a magic feature of "spreadsheet" mode where you can upload multiple files (eg, different formats) to a single item, simply by listing the archive.org `identifier` and `file` for each, with only the metadata from the first applying -- and, eg, the example for using spreadsheet mode shows missing the other fields out.  So any "must have these fields" should probably be limited to refusing to *create* a new item, but not have restrictions on uploading files to an existing item.

Ewen

**Comment by jjjake** [comment]
I agree with everything in your last comment @ewen-naos-nz.

I'm leaning towards requiring the user provide mediatype and collection at time of item creation, pointing to thorough documentation and suggestions in the error message. I think this should be required at the Python API level (i.e. not just `ia upload --spreadsheet...`).

I don't think this is, too, big of a burden for the user, and this way they will know exactly what to expect.

Long live Postel's Law @wumpus! ;-)

**Comment by ewen-naos-nz** [comment]
FWIW, I've figured out why they ended up in the `opensource` collection: [according to the documentation it is the default collection](https://internetarchive.readthedocs.io/en/latest/metadata.html#collection).  So nothing to do with the subject tags.

It *may* make sense to continue that default for one-off uploads (although personally I'd lean towards "explicit is better than implicit" for things that cannot easily be changed later).  But in the spreadsheet/multiple-create case I definitely think it'd be best to only *create* with an explicit specification of `collection` (and `mediatype`) to stay consistent with the principle of least surprise.  In the spreadsheet case it doesn't take much extra effort to specify the `collection` and `mediatype` for each item (even if making the spreadsheet by hand).

Ewen

**Comment by jjjake** [comment]
I'm with you @ewen-naos-nz (leaning towards "explicit is better than implicit, but it could be a bit annoying for one-off uploads).

What about requiring a collection, unless a default collection is specified in the config file?

**Comment by ewen-naos-nz** [comment]
Requiring a collection to be specified directly, unless one is specified in the config file seems fine to me.  Actually specifying one in the config file seems like a sufficient explicit step to me.  (It's just "default defaults" which catch people out :-) )

FTR, having now asked for collections to be created to upload these bulk sets into, it turns out that the archive.org staff create them only after there are 50+ identifiers with a common theme *already on the archive*.  So it seems like the first 50+ uploads need to go into `opensource` *anyway*, and then archive.org staff have to manually move them when creating the collection.  (But FWIW, I do think it'd be safer for "new users" of the bulk uploader if they had to make an explicit decision to upload somewhere other than the `test_collection`, as the bulk upload process means some "try it and fine tune" is going to be needed.)

Ewen

**Comment by ewenmcneill** [comment]
Closing issue (which I opened) to clean up my "reported" list, because after 3.5 years it seems unlikely to be spontaneously fixed now, and it's been years since I personally ran into the issue (not even sure if the defaults are still the same).

Ewen

**Comment by foghawk** [comment]
Having just run into a similar issue with `--file_metadata`, I strongly agree that creating new items should fail unless collection and mediatype are explicitly set.

(I don't think setting collection to `test_collection` is an acceptable substitute, since 'deleted' test items are actually only darked and still occupy their identifiers. This should probably also be in the documentation.)

Having read through the code, it looks to me like a check for `self.exists or all(key in metadata for key in ['collection', 'mediatype'])` (throwing some form of exception if it fails) at the beginning of `Item.upload_file` would be sufficient to implement this at the API level. Is that correct? I can put in a PR if you wish, although my knowledge of what other code paths would need testing is limited.

**Comment by ewenmcneill** [comment]
Reopening issue (which I created *years* ago) since it's just been confirmed to still exist as a problem, everyone seems to agree the default is... suboptimal, and there's been an offer of a PR.

@foghawk I'd suggest you create the PR anyway, in the hope that someone at the IA will accept it more easily than doing something with a description of a bug :-)

Ewen

**Comment by jjjake** [comment]
Thinking about this again, I don't think `ia` should default to the test_collection and I do think that `opensource` is a good default collection.
