### ISSUE TITLE
Parallel upload through command line

### ISSUE THREAD

**Issue by hargup** [jjjake/internetarchive#159]
Hello, I've download all the laws of Indian states from http://www.lawsofindia.org/ and then I'm uploading them to archieve.org, using the [command line tool](https://internetarchive.readthedocs.io/en/latest/cli.html). There are some five thousand files, I was wondering if there is an option to parallelize the upload process?

**Comment by jjjake** [comment]
Hi @hargup,

Are you familiar with the GNU `parallel` command-line tool?: https://www.gnu.org/software/parallel

This is what I usually use to parallelize uploads (as well as for other `ia` functions).

One thing to note with uploads, regardless of how you decide to submit concurrent uploads, is that it does not really pay to upload to a single item concurrently. It is recommended to upload to different items in parallel.

A basic example might be something like: Let's say you have a list of identifiers you would like to create/upload to in a file called itemlist.txt:

    my_id1
    my_id2
    my_id3

With files named like `<identifier>.pdf`. Then, you could use parallel like so:

    parallel 'ia upload {} {}.pdf -m collection:my_collection -m mediatype:texts --retries 30' < itemlist.txt

I usually do something like this, providing minimal metadata that is the same across all items (e.g. collection, mediatype), and then add unique metadata after the upload has completed (i.e. `ia metadata --spreadsheet=metadata.csv`).

Does this make sense? Please feel free to email me if you have more questions that are specific to your use case, otherwise followup here.

Thanks for the good question, I hope this helps! : )

**Comment by hargup** [comment]
Thank you that helped. It would be very convenient to have a command line flag to `ia upload --spreadsheet=metadata.csv` to do the parallelization.

**Comment by mlissner** [comment]
This is in the docs now and it feels like something that doesn't need to be part of this library. Should we close this issue?
