### ISSUE TITLE
Unable to change an item's file "format" entry

### ISSUE THREAD

**Issue by ghost** [jjjake/internetarchive#228]
I have an item on IA where some of the files in the item are wrongly detected as being "DV Video" and "Advanced Audio Coding".

https://archive.org/details/2813_d64_C64_roms_wwwC64com

I am not sure if i'm using the "ia" command-line tool correctly or not, when trying to change the "format" entry of these files. But, based off of https://internetarchive.readthedocs.io/en/latest/cli.html#metadata , I've tried e.g:

`ia metadata 2813_d64_C64_roms_wwwC64com --target="Metal_Warrior_3.d64" --modify="format:Unknown"`

to change that specific file from  "_DV Video_" to "_Unknown_", as well as trying

`ia metadata 2813_d64_C64_roms_wwwC64com --target=Metal_Warrior_3.d64 --modify=format:Unknown`

Neither of the commands however seem to change the format entry of the item's file..

**Am I simply using incorrect arguments or is something perhaps going wrong elsewhere?**

The log for the item is here, including the 2-4 [last attempt](https://catalogd.archive.org/log/788533120)s trying to run the commands above: https://catalogd.archive.org/history/2813_d64_C64_roms_wwwC64com

(ia --version = 1.7.4)

**Comment by DuckHP** [comment]
Just for curiousity, i tried
` ia -d metadata 2813_d64_C64_roms_wwwC64com --target="files/Metal_Warrior_3.d64" --modify="format:Unknown"`

which give me:

> 2813_d64_C64_roms_wwwC64com - error (400): Modification or addition of intrinsic property 'format' not allowed

Even though i would be able to change the format if i were to do it trough the browser_(?)_

**Comment by jjjake** [comment]
Thanks for the report, @DuckHP. This is either a bug in the browser editor, or the Metadata API. I'm guessing it's a bug in the Metadata API (i.e. you should be allowed to modify this field via the Metadata API), but I'll have to confirm that. If so, hopefully we can get it fixed ASAP.

I'll report back here once I have more details.

**Comment by DuckHP** [comment]
Unable to 100% confirm it yet, but there also seem to be inability to use  `--append=subject:<topic>` Stephen_Bax_provisional_partial_decoding_Voynich_manuscript --append=subject:phytotherapy

**Comment by p8NG6L** [comment]
Today, using `ia` version 1.8.1, I was able to set a file's `format` metadata—but after setting it once, I could not change it to something else.

1. I uploaded a file with the filename extension ".test" so that its format would not be guessed automatically.
2. I checked https://archive.org/metadata/TEST_metadata_format_api and saw `"format": "Unknown"` under `"hello.test"`.
3. I first tried changing the metadata field using a Python program:
   ```
   item.modify_metadata({"format": "ZIP"}, target="files/hello.test")
   ```
   It did not work:
   ```
   {"success":false,"error":"Modification or addition of intrinsic property 'format' not allowed"}
   ```
4. Then using the command-line `ia metadata`, I was able to change the field and verify that it was correctly changed at https://archive.org/metadata/TEST_metadata_format_api:
   ```
   $ ia metadata TEST_metadata_format_api --modify=format:'Item Image' --target 'files/hello.test'
   TEST_metadata_format_api - success: https://catalogd.archive.org/log/2728934612
   ```
   The catalog shows:
   ```
   Patching target 'files/hello.test'
   Target file is is 'hello.test'
   Original file properties:
   Array
   (
       [source] => original
       [mtime] => 1629063364
       [size] => 122
       [md5] => fcd251a6a25191b0718882f1cb884562
       [crc32] => 97cbf2bf
       [sha1] => bcec2ea28f49924814dfd0550d1c7a3e52c936ba
       [format] => Unknown
       [viruscheck] => 1629063726
   )

   Applying patch '[{"op": "replace", "path": "/format", "value": "Item Image"}]'
   Patched file properties:
   Array
   (
       [source] => original
       [mtime] => 1629063364
       [size] => 122
       [md5] => fcd251a6a25191b0718882f1cb884562
       [crc32] => 97cbf2bf
       [sha1] => bcec2ea28f49924814dfd0550d1c7a3e52c936ba
       [format] => Item Image
       [viruscheck] => 1629063726
   )
   ```
5. I then tried to change the metadata field to something else, and it did not work:
   ```
   $ ia metadata TEST_metadata_format_api --modify=format:'ZIP' --target 'files/hello.test'
   TEST_metadata_format_api - error (400): Modification or addition of intrinsic property 'format' not allowed
   ```
6. Attempting to set the field to its current value shows a different message:
   ```
   $ ia metadata TEST_metadata_format_api --modify=format:'Item Image' --target 'files/hello.test'
   TEST_metadata_format_api - warning (400): no changes to _files.xml
   ```
7. I thought perhaps if I deleted the field, I would be able to set it again, but I did not find a way to remove a field from a single file, because `ia metadata --remove` does not accept the `--target` option the way `ia metadata --modify` does. I tried `REMOVE_TAG`, but that did not work either:
   ```
   $ ia metadata TEST_metadata_format_api --modify=format:'REMOVE_TAG' --target 'files/hello.test'
   TEST_metadata_format_api - error (400): Modification or addition of intrinsic property 'format' not allowed
   ```
