### ISSUE TITLE
Search requires authentication?

### ISSUE THREAD

**Issue by yurivict** [jjjake/internetarchive#239]
Docs say that authentication is required for uploads and downloads of restricted content:  https://internetarchive.readthedocs.io/en/latest/quickstart.html#configuring

But ```ia``` asks for credentials even for a simple search.
The website doesn't require being logged in for search.

**Comment by jjjake** [comment]
Yes, `ia search` requires authentication. I'll update the docs.

**Comment by yurivict** [comment]
> Yes, ia search requires authentication. I'll update the docs.

Is this because their API permissions are more restrictive than the webpage search, or this is just not implemented in ```ia```?

**Comment by jjjake** [comment]
As of right now the API itself does not require authentication (http://archive.org/help/aboutsearch.htm), but it likely will someday.

It is required in `ia` because it is useful for us to have search requests associated with an account so we can reach out to the user if their queries are causing issues. In the future we would also like to add rate-limiting to the API, which will require authentication. This is a step towards that direction, as well as a useful tool for us in resolving issues caused by expensive search queries or by getting overwhelmed by requests.

**Comment by yurivict** [comment]
You introduce politics here. It's not required, but you require it because of some considerations.
There are people who are allergic to creating accounts, and I happen to be one of them. :)
