### ISSUE TITLE
Passing single quote in subject metadata

### ISSUE THREAD

**Issue by geedublya** [jjjake/internetarchive#262]
Apologies if this has been answered a million times and/or is blindingly obvious, but I'm a bit new to all of this. 

I'm trying to write an Apple Script that will pass information to IA, e.g. --metadata='subject:women's history'. 

My struggle is figuring out how to tell Apple Script to pass along the single quote in a way that the shell script will recognize. 

Appreciate any and all information that points me in the right direction. 

With thanks!
George

**Comment by jjjake** [comment]
I'm not very familiar with Apple Script, but are you able to double quote the value instead of using single quotes (i.e. `--metadata="subject:women's history"` instead of `--metadata='subject:women's history'`)? Or escape the single quote (i.e. `--metadata='subject:women\'s history'`)?

Where is Apple Script getting the `--metadata` value from? Is it always the same, is it human input, or is it automatically generated somehow?

Sorry I can't be more helpful. If you're able to provide more details on what you're trying to do, I might be able to help more or provide alternatives to Apple Script (feel free to email me if you'd prefer, my email is on my profile).

**Comment by geedublya** [comment]
Thanks! 

So, the goal is to write an AppleScript to take human input to feed to the IA software. 

My understanding is that the IA command line needs tags with a single quote, i.e.: 

--metadata='subject:the_subject'

If I'm able to use double-quotes instead, that would certainly help. I'll update my code and give it a try now.

**Comment by jjjake** [comment]
Double quotes will work just fine, though you might get unexpected results depending on what the input is.

For example, try this in your terminal:

    $ echo "hi $foo"
    hi
    $ echo 'hi $foo'
    hi $foo

You might find this stackoverflow question informative: https://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash

Poking around a bit more about how to escape user input in Apple Script, I found these two pages:

https://discussions.apple.com/thread/2512634
https://stackoverflow.com/questions/8138167/how-can-i-escape-shell-arguments-in-applescript

It seems that there might be some sort of Apple Script function `quoted form`? I think that might be what you want.

Again, I'm not familiar with Apple Script, so take all of this with a grain of salt and remember that you want to be very careful about quoting and escaping user input.

Can you point me to your Apple Script?

**Comment by geedublya** [comment]
Using double quotes instead of single quotes, plus adding some error proofing to ensure I don't pass a double quote through, is doing the trick very nicely!

i.e.:
--metadata="subject:the_subject"

instead of 

--metadata='subject:the_subject'.

Many thanks!!
