### ISSUE TITLE
Setting thumbnail & item image

### ISSUE THREAD

**Issue by ahundt** [jjjake/internetarchive#279]
1. Is there an API example for setting item thumbnail & item image?
2. Are there restrictions on the thumbnail dimensions & file type?

I looked through the documentation and past issues. I could not find an example of how to correctly specify this in a script. Thanks!

**Comment by jjjake** [comment]
You can upload an image named in the format `<identifier>_itemimage.jpg`, or set the format of the image manually after upload:

```ia metadata <identifier> --target 'files/foo.jpg' --modify 'format:Item Image'```

```>>> item.modify_metadata(dict(format='Item Image'), target='files/foo.jpg')```

**Comment by ahundt** [comment]
I'm having trouble finding the `--modify` option for the thumbnail and I can't simply hit the `edit` button on the webpage because there are too many files and it won't finish loading. 

I also ran:
``
$ ia metadata johns_hopkins_costar_dataset --target 'files/2018-06-21-23-21-49_example000004.success_tiled.jpg' --modify 'format:Item Image'
johns_hopkins_costar_dataset - success: https://catalogd.archive.org/log/1044360613
```

It looks like the task finished but [the item doesn't show the item image](https://archive.org/details/johns_hopkins_costar_dataset).

Sorry for having so many questions/issues!

**Comment by jjjake** [comment]
Ah, it looks like this is an issue due to the number of files in the item. Our website cannot parse the files.xml, and therefore is not able to find an item image.

As a rule of thumb, we generally don't recommend uploading more than 10,000 files to an item. See the following documentation for more suggestions:

https://archive.org/services/docs/api/items.html

I alerted our front end team, and this is a known issue. It doesn't sound like a fix is being worked on currently, but hopefully it can be addressed someday. If you have anymore questions about this bug, I'd recommend emailing info@archive.org.

My apologies for the trouble. In the future, I would recommend sharding your data into more items. If you have any questions about this, or need help creating a collection, feel free to email me (my email is on my profile).
