### ISSUE TITLE
Feature request: improve download + progress indicator

### ISSUE THREAD

**Issue by ahundt** [jjjake/internetarchive#280]
I think there are two areas which would make for a really nice improvement in the download command. Thanks for all your help up to this point, particularly considering the flurry of issues and questions I've had during the upload process.

### 1. Improve download feedback with progress bar

First, I love how easy the download instructions can be with this tool, the entirety of my current download instructions are so simple!
```
cd ~/ 
# pip install internetarchive
# We hope to eventually switch to the above line
pip install -e 'git+https://github.com/RexxarCHL/internetarchive#egg=internetarchive' --user --upgrade
mkdir -p ~/.keras/datasets/costar_block_stacking_dataset_v0.4
cd ~/.keras/datasets/costar_block_stacking_dataset_v0.4
ia download johns_hopkins_costar_dataset
```
However, here is what the download looks like for me after starting it 24 hours ago:
```
$ ia download johns_hopkins_costar_dataset
johns_hopkins_costar_dataset: ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
```
It is very difficult to tell what is happening here, so I think it would be helpful to get a count of the files in an item and show a progress bar.  I use https://github.com/tqdm/tqdm in my own projects.

### 2. Download via torrent files by default

I believe the download is proceeding at 500KB per second so for my 0.5TB dataset that will (hopefully) take 3 days to download. Might I suggest that `ia download` try to utilize archive.org's automatically created torrent files first, then fall back on the regular download process if that doesn't work?

While I was browsing the internet archive I found http://academictorrents.org, which looks like it [uploads to the internet archive](https://archive.org/details/academictorrents) & has some overlapping goals. It looks like they have some straightforward python torrent code you might be able to utilize with an MIT license:

https://github.com/AcademicTorrents/at-python

I haven't tested it though. :-)

#### related side note: archive.org's torrent files

I'd simply create torrent based download instructions in the first place, but no torrent was created for [my dataset on archive.org](https://archive.org/details/johns_hopkins_costar_dataset). The problem seems to be [because the item was too big](https://catalogd.archive.org/log/1043544239):

```
"SKIPPING UPDATE to johns_hopkins_costar_dataset_archive.torrent IN /t/derive/johns_hopkins_costar_dataset... item (502876 MB) exceeds maximum size (256000 MB)"
```

I sent an email about this (sorry for the redundancy) but I wanted to mention that here so there is some additional context regarding why my [download instructions](https://sites.google.com/site/costardataset/download) don't simply utilize the torrent.

**Comment by JustAnotherArchivist** [comment]
I'm in favour of progress bars on `ia download`. A file count is tricky since `Item.get_files` is a generator, but default verbose output with file-by-file progress bars like `ia upload` sounds good to me. (tqdm is already a dependency these days for the uploads.)

I'm not a fan of integrating a torrent client though. That adds significant complexity and error sources. I think that's better done with a dedicated torrent software. The torrent file itself can of course already be downloaded with `ia download` and the `--glob` option for example. By the way, the `academictorrents` package you mentioned is specific to their tracker and seems to be somewhat abandoned, not supporting any current version of Python.

**Comment by JustAnotherArchivist** [comment]
@jjjake Thoughts on overhauling that aspect of `ia download` and `Item.download` to match the uploading?

The current situation is as follows:

* `Item.upload[_file]` has a `verbose` kwarg which defaults to a falsy value. No output is produced at all by default. With `verbose = True`, you get the progress bar etc.
* `ia upload` defaults to setting that `verbose` kwarg to `True` unless `--quiet` is specified.
* `Item.download` and `File.download` have `verbose` and `silent` kwargs. `verbose` defaults to `False` whereas `silent`'s default value depends on other arguments (`True` if a file-like object is passed as the download target, else `False`). This produces the `dddd...` output by default. `verbose = True` produces one output line per file (`downloaded item/file to item/file` and `skipping item/file, file already exists` etc.), else `silent = True` suppresses all output.
* `ia download` defaults to setting both of those to `False`. It has `--verbose` and `--silent` options to enable either of the other output modes.

So I'd remove the `silent` kwarg and replace the `--verbose` and `--silent` options with `--quiet`, which is disabled by default. The special file-like object treatment isn't needed even with `--stdout` because progress bars and skip messages can go to stderr (tqdm does that by default anyway). (Which reminds me that there is a lot of inconsistency in general about whether things get printed to stdout or stderr. We should clean that up as well.)

How does that sound to you?

**Comment by jjjake** [comment]
All of that sounds great @JustAnotherArchivist! I support all of the changes you mentioned, and would be happy to see the inconsistencies of what gets printed to stdout or stderr cleared up. Thanks again, I appreciate it!
