### ISSUE TITLE
The --retries flag isn't working for ia download

### ISSUE THREAD

**Issue by jakewilliami** [jjjake/internetarchive#337]
Using `ia` version 1.9.3.  I am running, for example
```
ia download bangla-tutoria-book 'Advanced Excel 2013 Bangla Book .gif' --retries 10
```
However, this is just giving me the download usage help message (as if the syntax isn't correct).  I have checked the docs and source code and it seems that I am using the `--retries` flag correctly.  I downloaded internetarchive via `pip3` on my Apple machine.

**Comment by maxz** [comment]
Your comment just helped me to solve this, @JustAnotherArchivist.
I looked at all parts of this except for the usage listing, because I wrongly assumed that this would not matter.

The documentation for `docopt` is really bad by the way. When I began troubleshooting this I tried to gain the required knowledge by reading the documentation, but it is almost non-existent.
