### ISSUE TITLE
Error in internetarchive setup command

### ISSUE THREAD

**Issue by psubhashish** [jjjake/internetarchive#361]
Hi, I'm trying to set up IA for the first time. I am currently at the site package installation part of the step "[Get The Code](https://archive.org/services/docs/api/internetarchive/installation.html#get-the-code)". When I run `python setup.py install` it shows me an error message
`error in internetarchive setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in backports.csv < 1.07;python_version<"2.7" at ;python_version<"2.7"`. What am I doing wrong?

**Comment by JustAnotherArchivist** [comment]
What are your Python and setuptools versions?

`python --version`
`python -m easy_install --version`

**Comment by psubhashish** [comment]
Python 2.7.10, setuptools 18.5

**Comment by JustAnotherArchivist** [comment]
Python 2 is EOL. In addition, 2.7.10 is very old (2015), and there have been various security fixes since then.
setuptools 18.5 is similarly ancient (Nov 2015), and the `python_version` marker was [added in version 20.5 (and stable since 20.8.1)](https://stackoverflow.com/a/32643122).

You should update your system to current and supported software versions.

**Comment by jjjake** [comment]
@psubhashish Are you able to update setuptools? I believe that should resolve this issue.
