### ISSUE TITLE
Add option to exclude derivatives on downloads

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#365]
As far as I can see, there is no direct way to download only original files through the CLI. Not using `--on-the-fly` merely excludes certain formats that are not stored at IA but generated as needed. I suggest adding a `--exclude-derivatives` option that does what it says on the tin. Example use case is downloading an audio or video item without downloading several copies of the content (even if the original files have varying formats and a `--glob` filter doesn't work well due to that) or simply retrieving exactly what was originally uploaded into the item (e.g. for mirroring purposes).

**Comment by seth1** [comment]
An alternative could be something like:
ia download --formats=original,derivative,meta.

**Comment by rudluff** [comment]
Sorry to necro, but this seems useful to post publicly. This can be accomplished with a bash script:

```
#!/bin/bash

for f in ` ia list -a $@ | grep original | awk '{print $1}' ` ; do 
    ia download $@ "$f" ; 
done
```

**Comment by JustAnotherArchivist** [comment]
Yeah, it can be done externally. Here's a more solid approach with `jq` that doesn't break e.g. if a filename contains 'original' or spaces or other weird characters:

    ia metadata "${identifier}" | jq -j '.files[] | if .source == "original" then .name + "\u0000" else empty end' | xargs -0 ia download "${identifier}"

**Comment by jjjake** [comment]
Thanks for the workaround @rudluff!

I like ghost's suggestion (though note that we're talking about the `source` field in files.xml rather than `format`). @JustAnotherArchivist what do you think of [this](https://github.com/jjjake/internetarchive/pull/585/files)? I added two new options to both the Python API and the CLI to only download files that have a given source and also to exclude files of a given source (so to skip download derivatives: `ia download <id> --exclude-source derivative`).

**Comment by JustAnotherArchivist** [comment]
@jjjake Haven't tested it, but that looks great!
