### ISSUE TITLE
local pdf verify before upload

### ISSUE THREAD

**Issue by ahmedtds** [jjjake/internetarchive#388]
Hi, I'm really sick of this error: "Uploaded content is unacceptable. - Syntax error detected in pdf data. You may be able to repair the pdf file with a repair tool, pdftk is one such tool"

Every pdf reader opens the files without issue but internet archive complains. Worst part is getting it after uploaded the file. Can you implement same verification code internet archive server uses on local to check the pdf files -before- uploading them, so first, we won't waste time by uploading it first and then getting the error, second it would be more convenient to get a list of files to attempt to repair instead of dealing with uploads interrupted one by one etc..

Thanks.

**Comment by jjjake** [comment]
This isn't something I think we would want to add to the library because it relies on the `pdfinfo` command, and we want to keep the library as portable as possible.

I suggest using the `pdfinfo` command before your uploads. If something like `pdfinfo foo.pdf` exits with `0`, your pdf should make it through fine.

Sorry for the inconvenience, and thank you for taking the time to provide feedback!

**Comment by ahmedtds** [comment]
Thanks for the info about pdfinfo, I will do that.
Do you know pdf repair tools other than pdftk btw?

**Comment by jjjake** [comment]
I don't have any other recommendations. Were you having issues with `pdftk`? Feel free to email me, if that's easier (email is on my profile).
