### ISSUE TITLE
`XDG_CONFIG_HOME` is not respected

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#400]
The primary config file location is currently hardcoded as `~/.config/ia.ini`. Instead, it should use the `XDG_CONFIG_HOME` environment variable if set, defaulting to `${HOME}/.config` ([specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)).

I'll fix this together with #399 but wanted to file an issue anyway so it isn't forgotten.

**Comment by jjjake** [comment]
Adding support for `XDG_CONFIG_HOME` sounds like a good idea to me. I do not want to create `${HOME}/.config` if it doesn't exist though. Let's use `XDG_CONFIG_HOME` if it exists, then try `${HOME}/.config` if it is not set, and then use `${HOME}/.ia` if `${HOME}/.config` doesn't exist.

**Comment by JustAnotherArchivist** [comment]
I just gave the XDG Base Directory spec a closer read. It actually requires the creation of the directory if it does not exist:

> If, when attempting to write a file, the destination directory is non-existant an attempt should be made to create it with permission `0700`.

So if proper support of the full spec is the goal (and I think it should be), there's no option not to create it...

Is there a specific reason why you don't want to have it created?

**Comment by OrionRandD** [comment]
If we just throw in "ia" inside "~/.config", it does not make any difference of having it in "~". 
Could you fix it to create, say, a "~/.config/archive/ia.conf" like most apps do?

**Comment by JustAnotherArchivist** [comment]
@OrionRandD It definitely makes a difference (e.g. version control on `${HOME}/.config`). But I tend to agree. While it isn't part of the XDG spec and there are exceptions, a subdirectory per software is a very common convention. I'd say `${HOME}/.config/internetarchive/ia.ini` in that case.

@jjjake?

**Comment by OrionRandD** [comment]
> @OrionRandD It definitely makes a difference (e.g. version control on `${HOME}/.config`). But I tend to agree. While it isn't part of the XDG spec and there are exceptions, a subdirectory per software is a very common convention. I'd say `${HOME}/.config/internetarchive/ia.ini` in that case.
> 
> @jjjake?

Can be.
Anyways, 
Could you show a practical example here on how to upload videos, docs and pictures using ia command line in the terminal? I find manpages and help, sometimes, very cryptic... Especially manpages - that Unix documentation mamoth...

**Comment by jjjake** [comment]
I'm fine with supporting `XDG_CONFIG_HOME`, as long as everything is backwards compatible with tests to make sure it doesn't break any existing configurations (i.e. `$HOME/.ia` and `$HOME/.config/ia` remain valid config locations).

I didn't want to create the directory because I wanted to keep things as simple as possible and leave the option of whether or not to use the `~/.config` dir/follow the `XDG_CONFIG_HOME` spec to the user. I just want to keep things simple and avoid introducing bugs and breaking changes for cosmetic changes.

I am not too concerned with the details here, but if we're moving this direction we should follow the spec as long as everything is backwards compatibility. Backwards compatibility is more important than following the spec though.

@OrionRandD You can refer to [the documentation](https://archive.org/services/docs/api/internetarchive/cli.html#upload) for examples and information on how to upload via the CLI.

**Comment by OrionRandD** [comment]
> I'm fine with supporting `XDG_CONFIG_HOME`, as long as everything is backwards compatible with tests to make sure it doesn't break any existing configurations (i.e. `$HOME/.ia` and `$HOME/.config/ia` remain valid config locations).
> 
> I didn't want to create the directory because I wanted to keep things as simple as possible and leave the option of whether or not to use the `~/.config` dir/follow the `XDG_CONFIG_HOME` spec to the user. I just want to keep things simple and avoid introducing bugs and breaking changes for cosmetic changes.
> 
> I am not too concerned with the details here, but if we're moving this direction we should follow the spec as long as everything is backwards compatible. Backwards compatibility is more important than following the spec though.
> 
> @OrionRandD You can refer to [the documentation](https://archive.org/services/docs/api/internetarchive/cli.html#upload) for examples and information on how to upload via the CLI.

Fair enough :)

**Comment by JustAnotherArchivist** [comment]
Fully agreed on backward compatibility of course. I'll prepare a PR that uses `${XDG_CONFIG_HOME}/internetarchive/ia.ini` by default and falls back to `~/.config/ia.ini` or `~/.ia`.
