### ISSUE TITLE
ia metadata : modify title and description not working

### ISSUE THREAD

**Issue by vvasuki** [jjjake/internetarchive#407]
The below does not work:

```
$ia metadata IndicTodayTalks --modify="title:Indic Today Talks"
IndicTodayTalks - error (400): Illegal tag name '"title'
$ia metadata IndicTodayTalks --append="title:Indic Today Talks" --append="description:Talks conducted by published by Indic Today on YouTube. Redistributed here with thanks for the convenience of those who prefer audio podcasts (automatically downloaded to their phones)"
IndicTodayTalks - error (400): Illegal tag name '"title'
$ia metadata IndicTodayTalks --append="title:Indic Today Talks"
IndicTodayTalks - error (400): Illegal tag name '"title'
```

What am I doing wrong?

**Comment by JustAnotherArchivist** [comment]
What shell are you using? This should work fine in standard shells like Bash, zsh, etc.

**Comment by vvasuki** [comment]
> What shell are you using?
xonsh

> This should work fine in standard shells like Bash, zsh, etc.

Thanks! bash indeed worked. But I don't understand why it failed with xonsh..

**Comment by JustAnotherArchivist** [comment]
This seems to be intentional in xonsh per [the documentation](https://xon.sh/tutorial_subproc_strings.html). And you're clearly not the only one confused by this behaviour, as evidenced by numerous reports in their issues (e.g. the ones mentioned in <https://github.com/xonsh/xonsh/issues/1432>). Perhaps `ia metadata identifier '--modify=title:Foo bar'` would work?

But yeah, this is a 'feature' of xonsh apparently, and internetarchive behaves as expected.

**Comment by vvasuki** [comment]
Ah I see - `ia metadata IndicTodayTalks '--append=title:Indic Today Talks'` indeed works. Thanks!
