### ISSUE TITLE
Creating an item with `ia copy` results in unexpected metadata

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#413]
Last night, I created https://archive.org/details/stackexchange_20210607 using this command (description removed for brevity):

    ia copy stackexchange/3dprinting.meta.stackexchange.com.7z stackexchange_20210607/3dprinting.meta.stackexchange.com.7z --metadata=mediatype:data --metadata=collection:opensource_media --metadata=date:2021-06-07 '--metadata=title:Stack Exchange Data Dump 2021-06-07' '--metadata=subject:Stack Exchange Data Dump' '--metadata=contributor:Stack Exchange Community' '--metadata=creator:Stack Exchange, Inc.' --metadata=description:snip

For comparison, here's the previous item: <https://archive.org/details/stackexchange_20210301>. The only difference between the two items is that the March one was created with `ia upload` from a local copy and the June one with the `ia copy` command above. Except for the changed dates, the `--metadata` options were exactly the same. As such, I would expect the items' metadata to be virtually identical as well. (The June item was also created with an older `ia` version than the March one, but I don't see any relevant changes in that part of the code since long before 1.9.3, so I'm not sure that's in any way relevant.)

Here are some notable oddities in the June item:

* It has two `mediatype` fields: `<mediatype>texts</mediatype>` and `<mediatype>data</mediatype>`
* It is part of the opensource collection: `<collection>opensource</collection>`
* It has two metadata fields that I've never seen before and one of which (`identifier-access`) is undocumented: `<identifier-access>http://archive.org/details/stackexchange_20210607</identifier-access>` and `<identifier-ark>ark:/13960/t5kb4rz3h</identifier-ark>`
* It has a `creator` field: `<creator>StackExchange</creator>`

None of these are present on the source item.

I suspect that all of this is a bug in the backend rather than `ia copy`, but since the latter is where it surfaces, I figured I'd file an issue here anyway. The texts mediatype and opensource collection values are the defaults when nothing else is specified, so apparently those get added even when others are present in the copy request. The two `identifier-*` ones are probably harmless but still odd. The creator field is the weirdest of all because it doesn't match *anything* as far as I can see; that specific spelling without a space and capitals doesn't seem to appear anywhere...

**Comment by maxz** [comment]
> Here are some notable oddities in the June item:
> 
> * It has two `mediatype` fields: `<mediatype>texts</mediatype>` and `<mediatype>data</mediatype>`
> * It is part of the opensource collection: `<collection>opensource</collection>`
> * It has two metadata fields that I've never seen before and one of which (`identifier-access`) is undocumented: `<identifier-access>http://archive.org/details/stackexchange_20210607</identifier-access>` and `<identifier-ark>ark:/13960/t5kb4rz3h</identifier-ark>`
> * It has a `creator` field: `<creator>StackExchange</creator>`

I can't follow your assessment.
None of those oddities appear in the metadata of  `stackexchange_20210607` for me.

Is this still an issue for you?

**Comment by JustAnotherArchivist** [comment]
Yes, all of these things are still present: https://archive.org/download/stackexchange_20210607/stackexchange_20210607_meta.xml

The mediatype on the item page is incorrect as a result (displaying as the texts icon instead of data). The collection appears in the sidebar. The `identifier-ark` item appears under the description. The `creator` appears together with the correct value (Stack Exchange, Inc.) under the title. The only one that doesn't seem to appear anywhere is the undocumented `identifier-access`.

I intentionally didn't ask yet for this item to be fixed so that it can serve as an example and the bug can be fixed.

**Comment by maxz** [comment]
Thank you for the additional information.

I could reproduce it. It is at least partially a bug in the `ia` command line tool, but also be a bug in the API endpoint.
Did you write a bug report to `info@archive.org`?

I have two ideas how to resolve this. One would be more elegant but I have to test it first, the other one will work guaranteed.

The first method would still contain at least the
```
<identifier-access>http://archive.org/details/stackexchange_20210607</identifier-access>
<identifier-ark>ark:/13960/t5kb4rz3h</identifier-ark>
```
since that comes somewhere from the backend.

The second method would essentially copy, filter and freshly create the metadata in a second step and therefore avoid this.

**Comment by JustAnotherArchivist** [comment]
I did not contact `info@`, mostly because my experience with that email address has been that of a black hole when it came to reporting bugs.

Which part of the issue do you think is in `ia`? I dug around in the source code and can't really find traces of anything. The default collection and mediatype don't appear anywhere in the code, for example. `ia copy`, as far as I can see, simply sends a `PUT` request to IA S3 with two extra headers `x-amz-copy-source` and `x-amz-metadata-directive` plus the metadata provided in the command line. So I think *all* of those oddities come from the IA backend somehow.

Also, users can't change the collection or mediatype after the item is created, so I don't think overwriting the modified metadata will work. (Surely uploads of the `_meta.xml` file get blocked, right?)

My workaround for now will be to download one of the files from the `stackexchange` item, upload that to the new item with `ia upload` and the correct metadata, and `ia copy` all other files. It's a bit silly but should work at least.

**Comment by maxz** [comment]
> Which part of the issue do you think is in ia?

The part that using `ia` leads to wrong results is a bug in my eyes. It should probably provide this functionality via other means as long as the backend behaves this way. It would be more useful to internally emulate the same API by calling 2-3 other ones than to have users deal with the problem of strange or even contradictory metadata.

You are right. The metadata problem would have to be solved differently, so it definitely has to be seen as a problem in the backend, because in its current form that API endpoint is mostly useless to regular users.
My second proposed workaround could not work with this endpoint in its current form but only when e. g. first creating the new item with its metadata and then copying all files separately using `CopyObject`.

I yet have to find the time to try the first one. (Checking if the desired behaviour can be achieved by using `x-amz-metadata-directive: replace` instead of `copy`.)
I'm not entirely sure how the endpoint is supposed to behave with that directive.
The best case would be that it would make the rest of the current program work as is, in the worst case the metadata would have to be fetched, modified and then provided to the copy call.

**Comment by JustAnotherArchivist** [comment]
Ah, right. Yeah, I agree, if this can't be fixed in a reasonable time frame on the backend, a workaround in the client emulating the functionality might be the best option. Is it possible to create an item with metadata without uploading any files?

**Comment by maxz** [comment]
At least the S3-like API allows for it. I'm not 100% sure about `ia` right now, by my intuition is that it is also possible.
If not, it should be trivial to implement due to the support in the backend. It's just like a regular upload / creation while simply omitting any non-header data.

**Comment by JustAnotherArchivist** [comment]
@maxz So I just tested this with the current `master` (e3065799). Sadly, it looks like this isn't entirely resolved yet.

I created https://archive.org/details/test_stackexchange_20210907 with

    ia copy stackexchange/3dprinting.meta.stackexchange.com.7z test_stackexchange_20210907/3dprinting.meta.stackexchange.com.7z --replace-metadata --metadata=...

using the same `--metadata` options as in the original comment in this issue except with updated dates and with `--metadata=collection:test_collection` instead of `opensource_media`. For the most part, that worked, but it still copied over the `licenseurl` (which shows up as 'Usage' on the web interface), `year`, and `backup_location` fields.
