### ISSUE TITLE
ia does not work on Windows anymore

### ISSUE THREAD

**Issue by darkstar** [jjjake/internetarchive#414]
Environment: Windows 7, 64 bit, Python 3.8.10 (also 64 bit)

ia version 1.9.6 works perfectly, but has trouble with larger files (uploads getting stuck). So I tried the current version, 2.0.3, and that bails out with a missing python dependency:
```
j:\>python d:\bin\ia --version
1.9.6

j:\>python d:\bin\ia2 --version
Traceback (most recent call last):
  File "D:\bin\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\bin\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\bin\ia2\__main__.py", line 65, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "d:\bin\ia2\.bootstrap\pex\variables.py", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "d:\bin\ia2\.bootstrap\pex\common.py", line 9, in <module>
ModuleNotFoundError: No module named 'fcntl'

j:\>python --version
Python 3.8.10

j:\>
```

**Comment by JustAnotherArchivist** [comment]
I assume you're using the binaries mentioned in the readme?

pex has never officially supported Windows, though it appears that older versions worked to some degree. Cf. https://github.com/pantsbuild/pex/issues/1155

**Comment by darkstar** [comment]
yup, I'm using the binaries from https://archive.org/download/ia-pex

I think the main problem is that it now uses `fcntl` (which it didn't before), and that module is not available on windows. I'm not too python-savvy, so I don't know if that module could be stubbed out on Windows. I tried it (by creating an almost-empty fcntl.py file with just the bare minimum that seems to be required to get it to run) but I was chasing down deeper and deeper after some weird errors about not being able to open files in my home directory or something.

If ia is not supposed to work on Windows then that's unfortunate but no big deal, I can still use the old version that runs and upload any files that it chokes on through the web client.

**Comment by JustAnotherArchivist** [comment]
I'm pretty sure it should work fine in principle on WSL. Possibly even on plain Windows, assuming you can install Python and packages there (I've left that world behind me a long time ago). But getting the *pex binary* to work on Windows again would certainly be a significant effort, and apparently nobody is interested in working on that since the [first issue about it](https://github.com/pantsbuild/pex/issues/9) could be in primary school by now...

To be clear, there's no particular reason (that I'm aware of) why `ia` wouldn't work on Windows. It doesn't use `fcntl` or any other Unixoid-only modules. It's only the pex packaging that already never supported Windows in the past and now broke due to changes in pex.

**Comment by Coloradohusky** [comment]
ia works for me (ia version 2.03, on Windows 10 though, not Windows 7), although I don't know what ia2 is, or pex

**Comment by jjjake** [comment]
Windows is not currently supported, though many report that it works for them. I would recommend using cygwin or a similar unix-like terminal, and installing via pip or source (rather than using the binary).
