### ISSUE TITLE
Why does search_items with an oai_updatedate return multiple values for one item?

### ISSUE THREAD

**Issue by voltagex** [jjjake/internetarchive#423]
I am trying to only scrape items that have been updated since I last ran a script, but the metadata I'm getting back is confusing

```python
import internetarchive
session = internetarchive.ArchiveSession()
search = session.search_items('collection:(archlinuxarchive)',fields=['identifier', 'oai_updatedate'])
for result in search:
    print(result)
```
might return something like

```python
{'identifier': 'archlinux_pkg_zynaddsubfx', 'oai_updatedate': ['2018-06-05T16:18:12Z', '2018-06-05T16:18:12Z', '2020-07-07T15:02:03Z']}    
{'identifier': 'archlinux_pkg_zziplib', 'oai_updatedate': ['2018-06-06T19:31:45Z', '2018-06-06T19:31:45Z', '2021-01-06T23:01:58Z']}        
{'identifier': 'archlinux_pkg_zzuf', 'oai_updatedate': ['2019-05-01T23:55:32Z', '2019-05-01T23:55:32Z', '2020-08-06T08:03:59Z']}
```

If I look at https://archive.org/metadata/archlinux_pkg_zzuf, at the time of writing the 'item_last_updated' property corresponds to '2020-08-06T08:03:59Z', so what are the other dates there?

It doesn't seem like I can request the item_last_updated field, what would be the "lightest" request I could make to the Archive here? I don't want to be burning too many resources while gathering data.

**Comment by JustAnotherArchivist** [comment]
From <https://archive.org/advancedsearch.php>:

> The special date field, "oai_updatedate", can be used to mean all of the following dates combined:
> * addeddate
> * indexdate
> * publicdate
> * reviewdate
> * updatedate

In that particular example, I guess it's addeddate, publicdate, and that non-metadata item_last_updated field.

You can filter by oai_updatedate in the search, e.g. `collection:archlinuxarchive oai_updatedate:[2021-01-01T00:00:00Z TO null]` would return only items in the collection that have been updated since the beginning of this year. (However, sorting by the field is not possible; see #226.)
