### ISSUE TITLE
Pretty Print ```ia metadata <identifier>``` Output

### ISSUE THREAD

**Issue by brandongalbraith** [jjjake/internetarchive#484]
I don't believe there's an option to "pretty print" the JSON blob that results from running ```ia metadata <identifier>```. Would a PR be welcomed (and merged) to do this (the equivalent of ```ia metadata <identifier> | python -m json.tool | pygmentize -l json``` )? Thanks!

**Comment by JustAnotherArchivist** [comment]
This needs some care. `ia metadata`, `ia search`, and `ia tasks` all actually produce JSONL output, not JSON. The pipeline above doesn't work when specifying more than one item, for example, because `json.tool` only expects a single object as input. Searching and task lists would almost always produce more than one line of output.

As for the actual implementation, it should simply require specifying `indent` and `separators` on the `json.dumps` call. However, `ujson` currently has segfault bugs in the `indent` code and doesn't support `separators` at all. The former is being worked on by the `ujson` maintainers, and the latter is something I wanted to tackle earlier this week (before I discovered more segfaults in relevant code, which need to be fixed first). So unless we want to effectively partially revert #470 and use the stdlib `json` again in those user-facing places, this would be blocked until the changes land in `ujson`, a new version of it is released, and we require that version here in `ia`.

**Comment by brandongalbraith** [comment]
Thanks @maxz and @JustAnotherArchivist for taking the time to review this suggestion. I'm adverse to introducing a cosmetic output change that could cause breakage (regarding single versus multiple objects returned), and it just so happens I came across jless (https://pauljuliusmartinez.github.io/) this evening, which I think will meet this need (improving the human consumption of ia JSON output) without extending ia.
