### ISSUE TITLE
Change `ia list` output from TSV to JSONL

### ISSUE THREAD

**Issue by JustAnotherArchivist** [jjjake/internetarchive#489]
`ia metadata`, `ia tasks`, and `ia reviews` all produce JSON or JSONL output. `ia list` is the only one with a similar type of output that still uses tab-separated values. I propose to replace this with JSONL as well.

A deprecation phase with a `--tab-output` option similar to `ia tasks` might be a good idea. It's still a breaking change, so doing that before 3.0 would be a good idea.

**Comment by jjjake** [comment]
I'm not sure how much `ia list` is even used, but the point of it was to **not** return JSON or JSONL. If you want JSONL, I'd suggest just using `ia metadata`:

```
ia metadata nasa | jq -c '.files[]'
```

I think if anything, the command could be removed. I'd prefer to keep it in, as to not break anything for anyone using it though.

I'd support a `--json` or `--jsonl` option for convenience, but not sure it's necessary since `ia metadata` exists?

**Comment by JustAnotherArchivist** [comment]
Oh, true, didn't think of that. Yeah, it is slightly redundant.

I'm using `ia list` fairly regularly to download things in parallel, but just the `--location` output, not the TSV. E.g. `ia search 'query' --itemlist | xargs -P 16 -I{} ia list {} --location | xargs -P 16 wget`. For that, it's much more pleasant than having to pipe things through `jq` to get the filenames and then construct the URLs manually. See also #412.

**Comment by jjjake** [comment]
Good to know you're using it regularly. I'm probably mistaken with my guess on how much it's used.

So what I'm thinking is `ia list` should be used for accessing metadata in convenient ways without having to parse JSON (e.g. the `--location` option), and if you need JSON(L) just use `ia metadata`?

Are there any other convenience options you'd like to see added (like `--location`)?
