### ISSUE TITLE
`--checksum` does not work when used with `--no-derive`

### ISSUE THREAD

**Issue by soredake** [jjjake/internetarchive#535]
When i execute `ia upload --checksum --verify --retries 10 --no-backup --no-derive something .` it's just starts uploading right away without checking checksums.

Windows 11, internetarchive 3.0.0 in powershell

**Comment by maxz** [comment]
I cannot replicate this on Linux. It would be the easiest if any contributor here had Windows 11 installed to verify this, because setting up Windows 11 in a VM is a bit of a pain thanks to the TPM requirement.

Could you run it while additionally using `--debug` as an argument and post the output here? This most likely will not produce anything helpful in debugging this, but maybe it does.

**Comment by soredake** [comment]
I think windows 10 vm are fine too, 11 is not that different from 10.

**Comment by maxz** [comment]
Cannot reproduce on Windows 10 with Python 3.10.5 and ia 3.0.2.

Retry with 3.0.2, and supply your Python version and debug output. Then I might take a look at it.
[Jake's stance](https://github.com/jjjake/internetarchive/issues/414#issuecomment-865250299) as of last year is that we do not officially support Windows.

**Comment by maxz** [comment]
You used unsupported syntax which just broke many file related mechanisms while still working due to sheer luck. I added support for it.
