### ISSUE TITLE
Some website content is not archived properly

### ISSUE THREAD

**Issue by vic233333** [jjjake/internetarchive#536]
Guess reason: Some sites are set up to redirect once when visited for anti-crawler and other purposes. The current archiving mechanism will either save the redirected page directly instead of the page you really want to save, or it will not save properly because of the redirect. If it is right, I recommend that when users manually archive pages with automatic redirection, they can choose to save the pages before and after the redirection. In addition, multiple redirects situations should also be considered.

For example
Website: NGA
Example URL: https://nga.178.com/read.php?tid=18483877
Problem: When searching, it will report an error as unable to archive, and when doing manual archiving, it will cause an error with status code 403.

Website: weibo
Example URL: https://weibo.com/5674786286/J0zwOcW1f
Problem: Manual archiving is possible, but only one redirect page is archived.
Example URL: https://web.archive.org/web/*/https://weibo.com
Problem: Archiving is available, but the status code of most archives in recent years is 302.

**Comment by maxz** [comment]
The Wayback Machine just archives redirects too.

Your examples seem to be working fine for me. You should go a bit more into what you see and what you expect so that it is understandable. I guess screenshots could help in this case.

But this is not the right place for reporting this anyways. You should only report problems with the command line utility `internetarchive` here.
Your report should probably be directed to `info@archive.org`.
