### ISSUE TITLE
Implicitly access items in collections

### ISSUE THREAD

**Issue by JesseWeinstein** [jjjake/internetarchive#90]
It would be nice if there was an easier way to get the items in a collection.

This could be implemented with a subtype of Item, called Collection, that would automatically run a search like `collection:[identifier]`, and could be iterated to produce the items in the collection.

If this sounds like a good approach, I'll code it up and send in a PR.

**Comment by jjjake** [comment]
@JesseWeinstein I think this idea sounds great. I would recommend working on the 1.0 branch, and subclassing from `internetarchive.item.BaseItem()`. Please let me know what I can do to support you. Thanks!

**Comment by JesseWeinstein** [comment]
Great, I'll start working on that!

**Comment by JesseWeinstein** [comment]
I'm confused about the intended difference between BaseItem and Item. Collections are Items, so I'm not sure why it would be better to subclass from BaseItem. Can you say more about that?

**Comment by JesseWeinstein** [comment]
https://github.com/jjjake/internetarchive/pull/91

**Comment by jjjake** [comment]
Regarding your question about subclassing from `BaseItem` vs. `Item`:

Good question. My initial thoughts were that the Item object contains methods that might not be fitting for a Collection object (i.e. Generally speaking, items shouldn't contain any files other than a few system files, however people often confuse "uploading to a collection" as uploading thousands of files to a single collection item).

But, now that I think of it, I think you have the right idea. Some of the Item methods, Collection objects should definitely have (i.e. modify_metadata). I think subclassing from Item makes sense. We can override any methods if necessary (perhaps restrict uploading to collection items, maybe Collection.download() downloads the whole collection (rather than just the files in the collection item), etc.).

The reason I created a BaseItem object at all is that I liked the idea of separating the data structure of an item from where it gets the data and what it does with it.

For example, I work on another library (https://github.com/jjjake/iamine) that is used for data-mining Archive.org item metadata and search results. I thought it might be useful to generalize some of the internetarchive library a bit more, so I could easily plug it in to something like iamine.

Does that make sense?

At any rate, any suggestions you have are warmly welcome!

**Comment by jjjake** [comment]
Pull request 92 is now merged into the 1.0 branch.
